import "dotenv/config";
import pg from "pg";

const { Pool } = pg;
const pool = new Pool();

const client = await pool.connect();

await client.query(`CREATE TYPE action_name AS ENUM ('payroll', 'purchase');`);

await client.query(`Create table users (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  balance integer CONSTRAINT no_null NOT NULL CHECK (balance >= 0) DEFAULT 0
);`);

await client.query(`Create table balance_changes (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id integer references users(id),
  action action_name,
  amount integer,
  ts timestamp DEFAULT CURRENT_TIMESTAMP
);`);

await client.query("INSERT INTO users(id, balance) VALUES(1, 500);");

await pool.end();
